# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "twarchiver"

sitename: "Twistory"
contactaddress: "contact@twistory.org"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "simple"

# template: "template_toolkit"
# engines:
#   template_toolkit:
#     ENCODING: 'utf8'
#     START_TAG: '[%'
#     END_TAG: '%]

logger: 'file'

log: debug

database: "data/twarchiver.db"

session: "YAML"

headericon: "header_icon.png"

downloadbatchsize: 100

historyquotes:
    - "History, history! We fools, what do we know or care. - Williams Carlos Williams" 
    - "History does not repeat itself. The historians repeat one another - Max Beerbohm" 
    - "History is a science, no more and no less. - J. B. Bury" 
    - "The past is always a rebuke to the present. - Robert Penn Warren" 
    - "A country without a memory is a country of madmen. - George Santayana" 
    - "History is interim reports issued periodically. - Anonymous" 
    - "History is philosophy teaching by example. - Thucydides" 
    - "History teaches everything, including the future. - Lamartine" 
    - "If you would understand anything, observe its beginning and development. - Aristotle" 
    - "Any time gone by was better - Jorge Manrique" 
    - "There is no history, only histories. - Karl Popper" 
    - "History is not melodrama, even if it usually reads like that. - Robert Penn Warren" 
    - "Who does not know that the first law of historical writing is the truth? - Cicero" 
    - "Writing intellectual history is like trying to nail jelly to the wall. - William Hesseltine" 
    - "History is the memory of things said and done. - Carl L. Becker" 
    - "History is always written wrong and so always needs to be rewritten. -  George Santayana" 
    - "It should be known that history is a discipline with a great number of approaches. - Ibn Khalduin" 
    - "The past does not influence me; I influence it. - Willem De Kooning" 
    - "Life must be lived forward, but it can only be understood backward. - Søren Kierkegaard" 
    - "History is a myth that men agree to believe. - Napolean" 
    - "History is the essence of innumerable biographies. - Thomas Carlyle" 
    - "The past does not repeat itself, but it rhymes. - Mark Twain" 
    - "History is not a science; it is a method. - Droyson" 
    - "We learn from history that we never learn anything from history. - Hegel" 
    - "Hope is the other side of history. - Marcia Cavell" 
    - "There exists no folly that men have not tried out. - Carl Jung" 
    - "The past is never dead; it's not even past. - William Faulkner" 
    - "The passion for tidiness is the historian's occupational disease. - Arthur M. Schlesinger" 
    - "What man is, only his history tells. - Wilhelm Dilthey" 
    - "History does not usually make sense until long afterward. - Bruce Catton" 
    - "History does not belong to us; we belong to it. - Hans-Georg Gadamer" 

