#!/usr/bin/perl

use DBIx::Class::Schema::Loader qw/ make_schema_at /;

make_schema_at(
    'Twarchiver::Schema',
    {
        use_namespaces => 1,
        dump_directory => './lib',
    },
    [ "dbi:SQLite:dbname=data/twarchiver.db", "", "", ],
);
